from datetime import datetime, timezone
from reportlab.platypus import Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

CERTIFICATE_TEMPLATE = """
<b>CERTIFICATE UNDER SECTION 65B OF THE INDIAN EVIDENCE ACT, 1872</b>

I, [OFFICER_NAME], [DESIGNATION], [UNIT], do hereby certify that:

1. The electronic records produced in this report are authentic and unaltered digital
   outputs derived from the original bank statement files listed in Appendix A.

2. Each source file was received in digital form and processed by FinFlow v2.2,
   a forensic analysis system. The SHA-256 hash of each source file is recorded
   in Appendix A and was verified before processing.

3. The analysis outputs contained herein — including transaction tables, fund flow
   graphs, pattern alerts, and financial calculations — were generated by automated
   rule-based and machine learning algorithms. These outputs are INVESTIGATIVE LEADS
   and have been reviewed by the undersigned before inclusion in this report.

4. This certificate is issued in accordance with Section 65B(4) of the Indian
   Evidence Act, 1872 and is intended for use in judicial and quasi-judicial
   proceedings.

Date: {date}
Place: {place}

Signed: _______________________
{officer_name}
{designation}
{unit}
Badge / Employee No.: {badge}
"""

def build_section_65b(styles, officer_info: dict) -> list:
    """Returns a list of ReportLab flowables for the 65B certificate page."""
    cert_text = CERTIFICATE_TEMPLATE.format(
        date=datetime.now(timezone.utc).strftime("%d %B %Y"),
        place=officer_info.get("place", "Bengaluru, Karnataka"),
        officer_name=officer_info.get("name", "[OFFICER NAME]"),
        designation=officer_info.get("designation", "[DESIGNATION]"),
        unit=officer_info.get("unit", "Karnataka CID EOW"),
        badge=officer_info.get("badge", "[BADGE NO.]")
    )
    style = ParagraphStyle("Cert65B", parent=styles["Normal"],
                           fontSize=9, leading=14, spaceBefore=6, spaceAfter=6)
    return [
        Paragraph("SECTION 65B CERTIFICATE", styles["Heading1"]),
        Spacer(1, 12),
        Paragraph(cert_text.replace("\n", "<br/>"), style)
    ]
