"""
Train Isolation Forest and LightGBM ensemble models from the rich synthetic
dataset generated by scripts/generate_training_data.py.

Run order:
  1. scripts/generate_training_data.py   (generates training_data.csv)
  2. scripts/train_models.py             (trains + saves both models)
  3. scripts/compute_hashes.py           (prints hashes to paste into model_loader.py)
"""
import os
import numpy as np
import pandas as pd
import joblib
from sklearn.ensemble import IsolationForest
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import roc_auc_score, classification_report
import lightgbm as lgb

MODEL_DIR   = os.getenv("MODEL_DIR", "/app/models")
DATA_PATH   = os.path.join(MODEL_DIR, "training_data.csv")
IF_PATH     = os.path.join(MODEL_DIR, "isolation_forest.joblib")
LGBM_PATH   = os.path.join(MODEL_DIR, "lgbm_weak.joblib")

FEATURE_NAMES = [
    "log_amount","is_round_500","is_round_1000","near_str","near_ctr",
    "hour_sin","hour_cos","day_of_week","is_weekend","is_off_hours",
    "amount_zscore","passthrough_ratio","retention_ratio","fan_out_ratio",
    "days_since_last","rolling_7d_count","rolling_7d_volume_log",
    "is_cash_related","narration_length_log","is_credit","has_counterparty",
    "raw_amount_log_clipped",
]

os.makedirs(MODEL_DIR, exist_ok=True)

if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        f"Training data not found at {DATA_PATH}. "
        "Run scripts/generate_training_data.py first.")

print(f"Loading training data from {DATA_PATH}...")
df = pd.read_csv(DATA_PATH)
print(f"  {len(df):,} rows, {(df['label']==1).sum():,} fraud")

X = df[FEATURE_NAMES].values.astype(np.float64)
y = df["label"].values

# ─── Isolation Forest ──────────────────────────────────────────────────────────
print("\nTraining Isolation Forest (contamination=auto)...")
X_normal = X[y == 0]
iforest = IsolationForest(
    contamination="auto",
    n_estimators=300,
    max_samples=min(10_000, len(X_normal)),
    random_state=42,
    n_jobs=-1,
)
iforest.fit(X_normal)       # fit on normal only - correct for anomaly detection
scores = iforest.decision_function(X)
fraud_scores_mean  = scores[y == 1].mean()
normal_scores_mean = scores[y == 0].mean()
print(f"  Fraud score mean:  {fraud_scores_mean:.4f} (lower = more anomalous)")
print(f"  Normal score mean: {normal_scores_mean:.4f}")
joblib.dump(iforest, IF_PATH)
print(f"  Saved -> {IF_PATH}")

# --- LightGBM -----------------------------------------------------------------
print("\nTraining LightGBM (weak supervision)...")
lgbm = lgb.LGBMClassifier(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=7,
    num_leaves=63,
    class_weight="balanced",
    colsample_bytree=0.8,
    subsample=0.8,
    subsample_freq=1,
    reg_alpha=0.1,
    reg_lambda=0.1,
    random_state=42,
    verbose=-1,
    n_jobs=-1,
)

# 5-fold cross-validation for honest AUC estimate
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
auc_scores = cross_val_score(lgbm, X, y, cv=cv, scoring="roc_auc", n_jobs=-1)
print(f"  Cross-validated AUC: {auc_scores.mean():.4f} +/- {auc_scores.std():.4f}")

# Train on full dataset
lgbm.fit(X, y)
preds = lgbm.predict(X)
print(f"\n  Full-data classification report:")
print(classification_report(y, preds, target_names=["normal", "fraud"]))

# Feature importance
importances = sorted(zip(FEATURE_NAMES, lgbm.feature_importances_),
                     key=lambda x: -x[1])
print("\n  Top 10 features by importance:")
for name, imp in importances[:10]:
    bar = "#" * int(imp / importances[0][1] * 20)
    print(f"    {name:<30} {bar} {imp:.0f}")

joblib.dump(lgbm, LGBM_PATH)
print(f"\n  Saved -> {LGBM_PATH}")

print("\n=== Training complete ===")
print("Run: python scripts/compute_hashes.py")
print("Then paste BOTH hashes into backend/ml/model_loader.py MODEL_HASHES")
